spring.application.name=jobboard

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/jobboard
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=clave-secreta-muy-larga-de-al-menos-256-bits-para-que-funcione
jwt.expiration=86400000

# Puerto
server.port=8081

logging.level.org.springframework.security=DEBUG